# Generated by Django 2.2.6 on 2019-10-10 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0002_auto_20191010_0111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unidad',
            new_name='Unidade',
        ),
    ]
