# Generated by Django 2.2.6 on 2019-10-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edificio', '0003_auto_20191010_0113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unidade',
            new_name='Unidad',
        ),
    ]
